export const durianClimateSeries = [
  {
    time: "06:00",
    airTemperature: 28.1,
    airHumidity: 86,
    soilMoisture: 84,
    nitrogen: 118,
    phosphorus: 44,
    potassium: 162,
  },
  {
    time: "08:00",
    airTemperature: 29.0,
    airHumidity: 82,
    soilMoisture: 82,
    nitrogen: 116,
    phosphorus: 43,
    potassium: 160,
  },
  {
    time: "10:00",
    airTemperature: 30.4,
    airHumidity: 77,
    soilMoisture: 79,
    nitrogen: 113,
    phosphorus: 42,
    potassium: 157,
  },
  {
    time: "12:00",
    airTemperature: 31.8,
    airHumidity: 71,
    soilMoisture: 75,
    nitrogen: 110,
    phosphorus: 40,
    potassium: 154,
  },
  {
    time: "14:00",
    airTemperature: 32.0,
    airHumidity: 69,
    soilMoisture: 71,
    nitrogen: 107,
    phosphorus: 39,
    potassium: 151,
  },
  {
    time: "16:00",
    airTemperature: 31.1,
    airHumidity: 73,
    soilMoisture: 73,
    nitrogen: 109,
    phosphorus: 40,
    potassium: 153,
  },
  {
    time: "18:00",
    airTemperature: 29.7,
    airHumidity: 79,
    soilMoisture: 78,
    nitrogen: 112,
    phosphorus: 42,
    potassium: 156,
  },
  {
    time: "20:00",
    airTemperature: 28.8,
    airHumidity: 83,
    soilMoisture: 81,
    nitrogen: 115,
    phosphorus: 43,
    potassium: 159,
  },
];

export const durianSensorStations = [
  {
    id: "station-khu-a",
    name: "Trạm Khu A",
    status: "ONLINE",
    lastSeen: "Vừa xong",
    battery: 86,
    device: "DHT22 + NPK RS485",
  },
  {
    id: "station-khu-b",
    name: "Trạm Khu B",
    status: "ONLINE",
    lastSeen: "2 phút trước",
    battery: 72,
    device: "DHT22 + Soil V2",
  },
  {
    id: "station-vuon-uom",
    name: "Trạm Vườn ươm",
    status: "MAINTENANCE",
    lastSeen: "35 phút trước",
    battery: 41,
    device: "DHT22",
  },
];
