export const durianTheme = {
  colors: {
    moss: "#2E5A44",
    mossDark: "#1E3D2D",
    mossSoft: "#DDE9E1",
    durianYellow: "#EED269",
    canvas: "#F5F7F3",
    surface: "#FFFFFF",
    surfaceSecondary: "#EEF4EF",
    ink: "#183126",
    muted: "#64746B",
    mist: "#A9B9B0",
    border: "#DCE6DF",
    white: "#FFFFFF",
    success: "#2E7D52",
    successSoft: "#E6F4EA",
    warning: "#B7791F",
    warningSoft: "#FFF4D6",
    danger: "#B84A3A",
    dangerSoft: "#FCECEA",
    info: "#2B6F8A",
    infoSoft: "#E7F3F8",
    blueSoft: "#E7F0ED",
  },
  typography: {
    display: { fontSize: 26, lineHeight: 32, fontWeight: "900" as const },
    title: { fontSize: 20, lineHeight: 26, fontWeight: "900" as const },
    section: { fontSize: 16, lineHeight: 21, fontWeight: "900" as const },
    body: { fontSize: 14, lineHeight: 21, fontWeight: "500" as const },
    bodyStrong: { fontSize: 14, lineHeight: 20, fontWeight: "800" as const },
    caption: { fontSize: 12, lineHeight: 17, fontWeight: "600" as const },
    label: { fontSize: 11, lineHeight: 15, fontWeight: "800" as const },
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 18, xxl: 22, xxxl: 28 },
  radius: { xs: 8, sm: 12, md: 16, lg: 22, pill: 999 },
  control: { minHeight: 48, iconButton: 44 },
  shadow: {
    card: { shadowColor: "#183126", shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  },
} as const;
